### ISSUE TITLE
Inserire le immagini .PNG

### ISSUE THREAD

**Issue by Josecontis** [bananale33/falso#6]
Aggiunta (o sostituire se già ci sono) le immagini .png in /res/img/guida-studente/
Le immagini sono:
• add_repo_coveralls.png
• Badge.png
• buildpath.png
• coveralls_no_badge.png
• coveralls+travis-badges.png
• create-json-key.png
• dashboard-api-service.png
• marketplace.png
• new-gcloud-project.png
• project-properties.png
• service-account-credentials.png

**Comment by Giovalo** [comment]
Aggiunte immagini in /res/img/guida-studente:
- add_repo_coveralls.png
- Badge.png
- buildpath.png
- coveralls_no_badge.png
- coveralls+travis-badges.png
- create-json-key.png

**Comment by Ocen5** [comment]
Aggiunte immagini in /res/img/guida-studente:

•dashboard-api-service.png
•marketplace.png
•new-gcloud-project.png
•project-properties.png
•service-account-credentials.png
